/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ProductsHandleRouteImport } from './routes/products/$handle'
import { Route as InvitationsTokenRouteImport } from './routes/invitations/$token'
import { Route as CollectionsHandleRouteImport } from './routes/collections/$handle'
import { Route as CheckoutReturnRouteImport } from './routes/checkout/return'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AccountQuoteCartRouteImport } from './routes/account/quote-cart'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as AccountCompanyRouteImport } from './routes/account/company'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as AccountQuotesIndexRouteImport } from './routes/account/quotes/index'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AccountInvoicesIndexRouteImport } from './routes/account/invoices/index'
import { Route as AccountQuotesQuoteIdRouteImport } from './routes/account/quotes/$quoteId'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders/$orderId'
import { Route as AccountInvoicesInvoiceIdRouteImport } from './routes/account/invoices/$invoiceId'

const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsTokenRoute = InvitationsTokenRouteImport.update({
  id: '/invitations/$token',
  path: '/invitations/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountQuoteCartRoute = AccountQuoteCartRouteImport.update({
  id: '/quote-cart',
  path: '/quote-cart',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCompanyRoute = AccountCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountQuotesIndexRoute = AccountQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const AccountInvoicesIndexRoute = AccountInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountQuotesQuoteIdRoute = AccountQuotesQuoteIdRouteImport.update({
  id: '/quotes/$quoteId',
  path: '/quotes/$quoteId',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const AccountInvoicesInvoiceIdRoute =
  AccountInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => AccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/account/addresses': typeof AccountAddressesRoute
  '/account/company': typeof AccountCompanyRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/quote-cart': typeof AccountQuoteCartRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/account/': typeof AccountIndexRoute
  '/cart/': typeof CartIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/account/invoices/$invoiceId': typeof AccountInvoicesInvoiceIdRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/quotes/$quoteId': typeof AccountQuotesQuoteIdRoute
  '/account/invoices/': typeof AccountInvoicesIndexRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/account/quotes/': typeof AccountQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/company': typeof AccountCompanyRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/quote-cart': typeof AccountQuoteCartRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/account': typeof AccountIndexRoute
  '/cart': typeof CartIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/account/invoices/$invoiceId': typeof AccountInvoicesInvoiceIdRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/quotes/$quoteId': typeof AccountQuotesQuoteIdRoute
  '/account/invoices': typeof AccountInvoicesIndexRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/account/quotes': typeof AccountQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/account/addresses': typeof AccountAddressesRoute
  '/account/company': typeof AccountCompanyRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/quote-cart': typeof AccountQuoteCartRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/account/': typeof AccountIndexRoute
  '/cart/': typeof CartIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/account/invoices/$invoiceId': typeof AccountInvoicesInvoiceIdRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/quotes/$quoteId': typeof AccountQuotesQuoteIdRoute
  '/account/invoices/': typeof AccountInvoicesIndexRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/account/quotes/': typeof AccountQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/account/addresses'
    | '/account/company'
    | '/account/orders'
    | '/account/profile'
    | '/account/quote-cart'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/checkout/return'
    | '/collections/$handle'
    | '/invitations/$token'
    | '/products/$handle'
    | '/account/'
    | '/cart/'
    | '/collections/'
    | '/products/'
    | '/account/invoices/$invoiceId'
    | '/account/orders/$orderId'
    | '/account/quotes/$quoteId'
    | '/account/invoices/'
    | '/account/orders/'
    | '/account/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account/addresses'
    | '/account/company'
    | '/account/profile'
    | '/account/quote-cart'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/checkout/return'
    | '/collections/$handle'
    | '/invitations/$token'
    | '/products/$handle'
    | '/account'
    | '/cart'
    | '/collections'
    | '/products'
    | '/account/invoices/$invoiceId'
    | '/account/orders/$orderId'
    | '/account/quotes/$quoteId'
    | '/account/invoices'
    | '/account/orders'
    | '/account/quotes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/account/addresses'
    | '/account/company'
    | '/account/orders'
    | '/account/profile'
    | '/account/quote-cart'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/checkout/return'
    | '/collections/$handle'
    | '/invitations/$token'
    | '/products/$handle'
    | '/account/'
    | '/cart/'
    | '/collections/'
    | '/products/'
    | '/account/invoices/$invoiceId'
    | '/account/orders/$orderId'
    | '/account/quotes/$quoteId'
    | '/account/invoices/'
    | '/account/orders/'
    | '/account/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CollectionsHandleRoute: typeof CollectionsHandleRoute
  InvitationsTokenRoute: typeof InvitationsTokenRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
  CartIndexRoute: typeof CartIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token': {
      id: '/invitations/$token'
      path: '/invitations/$token'
      fullPath: '/invitations/$token'
      preLoaderRoute: typeof InvitationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/quote-cart': {
      id: '/account/quote-cart'
      path: '/quote-cart'
      fullPath: '/account/quote-cart'
      preLoaderRoute: typeof AccountQuoteCartRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/company': {
      id: '/account/company'
      path: '/company'
      fullPath: '/account/company'
      preLoaderRoute: typeof AccountCompanyRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/quotes/': {
      id: '/account/quotes/'
      path: '/quotes'
      fullPath: '/account/quotes/'
      preLoaderRoute: typeof AccountQuotesIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/account/invoices/': {
      id: '/account/invoices/'
      path: '/invoices'
      fullPath: '/account/invoices/'
      preLoaderRoute: typeof AccountInvoicesIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/quotes/$quoteId': {
      id: '/account/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/account/quotes/$quoteId'
      preLoaderRoute: typeof AccountQuotesQuoteIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/account/invoices/$invoiceId': {
      id: '/account/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/account/invoices/$invoiceId'
      preLoaderRoute: typeof AccountInvoicesInvoiceIdRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountOrdersRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountCompanyRoute: typeof AccountCompanyRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountProfileRoute: typeof AccountProfileRoute
  AccountQuoteCartRoute: typeof AccountQuoteCartRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountInvoicesInvoiceIdRoute: typeof AccountInvoicesInvoiceIdRoute
  AccountQuotesQuoteIdRoute: typeof AccountQuotesQuoteIdRoute
  AccountInvoicesIndexRoute: typeof AccountInvoicesIndexRoute
  AccountQuotesIndexRoute: typeof AccountQuotesIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountCompanyRoute: AccountCompanyRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountProfileRoute: AccountProfileRoute,
  AccountQuoteCartRoute: AccountQuoteCartRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountInvoicesInvoiceIdRoute: AccountInvoicesInvoiceIdRoute,
  AccountQuotesQuoteIdRoute: AccountQuotesQuoteIdRoute,
  AccountInvoicesIndexRoute: AccountInvoicesIndexRoute,
  AccountQuotesIndexRoute: AccountQuotesIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  CollectionsHandleRoute: CollectionsHandleRoute,
  InvitationsTokenRoute: InvitationsTokenRoute,
  ProductsHandleRoute: ProductsHandleRoute,
  CartIndexRoute: CartIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
